config/routes.rb
Rails.application.routes.draw do
#match ':controller(/:action(/:id(.:format)))', :via => :all
  resources :lcb_access_items
  resources :lcb_account_sheets
  resources :lcb_accounts
  resources :lcb_actions
  resources :lcb_cash_coupon_defs
  resources :lcb_cash_coupons
  resources :lcb_feed_backs
  resources :lcb_image_positions
  resources :lcb_financing_target_tags
  resources :lcb_financing_target_positions
  resources :lcb_financing_target_bids
  resources :lcb_financing_targets
  resources :lcb_klines
  resources :lcb_manager_users
  resources :lcb_menus
  resources :lcb_pics
  resources :lcb_registries
  resources :lcb_templates
  resources :lcb_user_package_items
  resources :lcb_withdraw_financing_target_bid_items
  resources :lcb_withdraws
  resources :lcb_user_rewards
  resources :lcb_user_banks
  resources :lcb_users
  resources :yunweis
#  namespace :admin do
#    resources :users
#  end
  match '/reg', to: 'lcb_users#new', via: 'get'
  match '/login', to: 'lcb_users#login', via: 'get'
  match 'about_us.htm', to:'lcb_users#about_us.htm',via:'get'
  match '/sui_cun_bao', to: 'lcb_users#sui_cun_bao',via:"get"
  match '/login1', to: 'lcb_users#login1', via: 'post'
#    namespace :admin do
#          resources :sessions, only: [:new]
#              match '/signin', to: 'lcb_users#new', via: 'get'
#         end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/apidoc.rb
class Apidoc < ApplicationRecord
end

app/models/blog.rb
module Blog
  def self.table_name_prefix
    'blog_'
  end
end

app/models/lcb_access_item.rb
class LcbAccessItem < ApplicationRecord
end

app/models/lcb_account.rb
class LcbAccount < ApplicationRecord
end

app/models/lcb_action.rb
class LcbAction < ApplicationRecord
end

app/models/lcb_feed_back.rb
class LcbFeedBack < ApplicationRecord
end

app/models/lcb_financing_target_position.rb
class LcbFinancingTargetPosition < ApplicationRecord
end

app/models/lcb_kline.rb
class LcbKline < ApplicationRecord
end

app/models/lcb_menu.rb
class LcbMenu < ApplicationRecord
end

app/models/lcb_pic.rb
class LcbPic < ApplicationRecord
end

app/models/lcb_registry.rb
class LcbRegistry < ApplicationRecord
end

app/models/lcb_template.rb
class LcbTemplate < ApplicationRecord
end

app/models/lcb_user.rb
class LcbUser < ApplicationRecord
end

app/models/lcb_user_bank.rb
class LcbUserBank < ApplicationRecord
end

app/models/lcb_withdraw.rb
class LcbWithdraw < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/yunwei.rb
class Yunwei < ApplicationRecord
end

app/controllers/lcb_financing_target_positions_controller.rb
class LcbFinancingTargetPositionsController < ApplicationController
  before_action :set_lcb_financing_target_position, only: [:show, :edit, :update, :destroy]

  # GET /lcb_financing_target_positions
  # GET /lcb_financing_target_positions.json
  def index
    @lcb_financing_target_positions = LcbFinancingTargetPosition.all
  end

  # GET /lcb_financing_target_positions/1
  # GET /lcb_financing_target_positions/1.json
  def show
  end

  # GET /lcb_financing_target_positions/new
  def new
    @lcb_financing_target_position = LcbFinancingTargetPosition.new
  end

  # GET /lcb_financing_target_positions/1/edit
  def edit
  end

  # POST /lcb_financing_target_positions
  # POST /lcb_financing_target_positions.json
  def create
    @lcb_financing_target_position = LcbFinancingTargetPosition.new(lcb_financing_target_position_params)

    respond_to do |format|
      if @lcb_financing_target_position.save
        format.html { redirect_to @lcb_financing_target_position, notice: 'Lcb financing target position was successfully created.' }
        format.json { render :show, status: :created, location: @lcb_financing_target_position }
      else
        format.html { render :new }
        format.json { render json: @lcb_financing_target_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lcb_financing_target_positions/1
  # PATCH/PUT /lcb_financing_target_positions/1.json
  def update
    respond_to do |format|
      if @lcb_financing_target_position.update(lcb_financing_target_position_params)
        format.html { redirect_to @lcb_financing_target_position, notice: 'Lcb financing target position was successfully updated.' }
        format.json { render :show, status: :ok, location: @lcb_financing_target_position }
      else
        format.html { render :edit }
        format.json { render json: @lcb_financing_target_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lcb_financing_target_positions/1
  # DELETE /lcb_financing_target_positions/1.json
  def destroy
    @lcb_financing_target_position.destroy
    respond_to do |format|
      format.html { redirect_to lcb_financing_target_positions_url, notice: 'Lcb financing target position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lcb_financing_target_position
      @lcb_financing_target_position = LcbFinancingTargetPosition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lcb_financing_target_position_params
      params.require(:lcb_financing_target_position).permit(:position, :financing_target_id, :sort_num, :end_time, :start_time, :id, :owner_id, :create_uid, :write_uid)
    end
end

app/helpers/apidocs_helper.rb
module ApidocsHelper
end

app/helpers/lcb_financing_target_positions_helper.rb
module LcbFinancingTargetPositionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/yunweis_helper.rb
module YunweisHelper
end

app/views/lcb_financing_target_positions/_form.html.erb
<%= form_for(lcb_financing_target_position) do |f| %>
  <% if lcb_financing_target_position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lcb_financing_target_position.errors.count, "error") %> prohibited this lcb_financing_target_position from being saved:</h2>

      <ul>
      <% lcb_financing_target_position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :position %>
    <%= f.text_field :position %>
  </div>

  <div class="field">
    <%= f.label :financing_target_id %>
    <%= f.text_field :financing_target_id %>
  </div>

  <div class="field">
    <%= f.label :sort_num %>
    <%= f.text_field :sort_num %>
  </div>

  <div class="field">
    <%= f.label :end_time %>
    <%= f.datetime_select :end_time %>
  </div>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= f.label :id %>
    <%= f.text_field :id %>
  </div>

  <div class="field">
    <%= f.label :owner_id %>
    <%= f.text_field :owner_id %>
  </div>

  <div class="field">
    <%= f.label :create_uid %>
    <%= f.text_field :create_uid %>
  </div>

  <div class="field">
    <%= f.label :write_uid %>
    <%= f.text_field :write_uid %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lcb_financing_target_positions/edit.html.erb
<h1>Editing Lcb Financing Target Position</h1>

<%= render 'form', lcb_financing_target_position: @lcb_financing_target_position %>

<%= link_to 'Show', @lcb_financing_target_position %> |
<%= link_to 'Back', lcb_financing_target_positions_path %>

app/views/lcb_financing_target_positions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lcb Financing Target Positions</h1>

<table>
  <thead>
    <tr>
      <th>Position</th>
      <th>Financing target</th>
      <th>Sort num</th>
      <th>End time</th>
      <th>Start time</th>
      <th>Id</th>
      <th>Owner</th>
      <th>Create uid</th>
      <th>Write uid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lcb_financing_target_positions.each do |lcb_financing_target_position| %>
      <tr>
        <td><%= lcb_financing_target_position.position %></td>
        <td><%= lcb_financing_target_position.financing_target_id %></td>
        <td><%= lcb_financing_target_position.sort_num %></td>
        <td><%= lcb_financing_target_position.end_time %></td>
        <td><%= lcb_financing_target_position.start_time %></td>
        <td><%= lcb_financing_target_position.id %></td>
        <td><%= lcb_financing_target_position.owner_id %></td>
        <td><%= lcb_financing_target_position.create_uid %></td>
        <td><%= lcb_financing_target_position.write_uid %></td>
        <td><%= link_to 'Show', lcb_financing_target_position %></td>
        <td><%= link_to 'Edit', edit_lcb_financing_target_position_path(lcb_financing_target_position) %></td>
        <td><%= link_to 'Destroy', lcb_financing_target_position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lcb Financing Target Position', new_lcb_financing_target_position_path %>

app/views/lcb_financing_target_positions/new.html.erb
<h1>New Lcb Financing Target Position</h1>

<%= render 'form', lcb_financing_target_position: @lcb_financing_target_position %>

<%= link_to 'Back', lcb_financing_target_positions_path %>

app/views/lcb_financing_target_positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Position:</strong>
  <%= @lcb_financing_target_position.position %>
</p>

<p>
  <strong>Financing target:</strong>
  <%= @lcb_financing_target_position.financing_target_id %>
</p>

<p>
  <strong>Sort num:</strong>
  <%= @lcb_financing_target_position.sort_num %>
</p>

<p>
  <strong>End time:</strong>
  <%= @lcb_financing_target_position.end_time %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @lcb_financing_target_position.start_time %>
</p>

<p>
  <strong>Id:</strong>
  <%= @lcb_financing_target_position.id %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @lcb_financing_target_position.owner_id %>
</p>

<p>
  <strong>Create uid:</strong>
  <%= @lcb_financing_target_position.create_uid %>
</p>

<p>
  <strong>Write uid:</strong>
  <%= @lcb_financing_target_position.write_uid %>
</p>

<%= link_to 'Edit', edit_lcb_financing_target_position_path(@lcb_financing_target_position) %> |
<%= link_to 'Back', lcb_financing_target_positions_path %>