config/routes.rb
Rails.application.routes.draw do
#match ':controller(/:action(/:id(.:format)))', :via => :all
  resources :lcb_access_items
  resources :lcb_account_sheets
  resources :lcb_accounts
  resources :lcb_actions
  resources :lcb_cash_coupon_defs
  resources :lcb_cash_coupons
  resources :lcb_feed_backs
  resources :lcb_image_positions
  resources :lcb_financing_target_tags
  resources :lcb_financing_target_positions
  resources :lcb_financing_target_bids
  resources :lcb_financing_targets
  resources :lcb_klines
  resources :lcb_manager_users
  resources :lcb_menus
  resources :lcb_pics
  resources :lcb_registries
  resources :lcb_templates
  resources :lcb_user_package_items
  resources :lcb_withdraw_financing_target_bid_items
  resources :lcb_withdraws
  resources :lcb_user_rewards
  resources :lcb_user_banks
  resources :lcb_users
  resources :yunweis
#  namespace :admin do
#    resources :users
#  end
  match '/reg', to: 'lcb_users#new', via: 'get'
  match '/login', to: 'lcb_users#login', via: 'get'
  match 'about_us.htm', to:'lcb_users#about_us.htm',via:'get'
  match '/sui_cun_bao', to: 'lcb_users#sui_cun_bao',via:"get"
  match '/login1', to: 'lcb_users#login1', via: 'post'
#    namespace :admin do
#          resources :sessions, only: [:new]
#              match '/signin', to: 'lcb_users#new', via: 'get'
#         end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/apidoc.rb
class Apidoc < ApplicationRecord
end

app/models/blog.rb
module Blog
  def self.table_name_prefix
    'blog_'
  end
end

app/models/lcb_access_item.rb
class LcbAccessItem < ApplicationRecord
end

app/models/lcb_account.rb
class LcbAccount < ApplicationRecord
end

app/models/lcb_action.rb
class LcbAction < ApplicationRecord
end

app/models/lcb_cash_coupon.rb
class LcbCashCoupon < ApplicationRecord
end

app/models/lcb_feed_back.rb
class LcbFeedBack < ApplicationRecord
end

app/models/lcb_kline.rb
class LcbKline < ApplicationRecord
end

app/models/lcb_menu.rb
class LcbMenu < ApplicationRecord
end

app/models/lcb_pic.rb
class LcbPic < ApplicationRecord
end

app/models/lcb_registry.rb
class LcbRegistry < ApplicationRecord
end

app/models/lcb_template.rb
class LcbTemplate < ApplicationRecord
end

app/models/lcb_user.rb
class LcbUser < ApplicationRecord
end

app/models/lcb_user_bank.rb
class LcbUserBank < ApplicationRecord
end

app/models/lcb_withdraw.rb
class LcbWithdraw < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/yunwei.rb
class Yunwei < ApplicationRecord
end

app/controllers/lcb_feed_backs_controller.rb
class LcbFeedBacksController < ApplicationController
  before_action :set_lcb_feed_back, only: [:show, :edit, :update, :destroy]

  # GET /lcb_feed_backs
  # GET /lcb_feed_backs.json
  def index
    @lcb_feed_backs = LcbFeedBack.all
  end

  # GET /lcb_feed_backs/1
  # GET /lcb_feed_backs/1.json
  def show
  end

  # GET /lcb_feed_backs/new
  def new
    @lcb_feed_back = LcbFeedBack.new
  end

  # GET /lcb_feed_backs/1/edit
  def edit
  end

  # POST /lcb_feed_backs
  # POST /lcb_feed_backs.json
  def create
    @lcb_feed_back = LcbFeedBack.new(lcb_feed_back_params)

    respond_to do |format|
      if @lcb_feed_back.save
        format.html { redirect_to @lcb_feed_back, notice: 'Lcb feed back was successfully created.' }
        format.json { render :show, status: :created, location: @lcb_feed_back }
      else
        format.html { render :new }
        format.json { render json: @lcb_feed_back.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lcb_feed_backs/1
  # PATCH/PUT /lcb_feed_backs/1.json
  def update
    respond_to do |format|
      if @lcb_feed_back.update(lcb_feed_back_params)
        format.html { redirect_to @lcb_feed_back, notice: 'Lcb feed back was successfully updated.' }
        format.json { render :show, status: :ok, location: @lcb_feed_back }
      else
        format.html { render :edit }
        format.json { render json: @lcb_feed_back.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lcb_feed_backs/1
  # DELETE /lcb_feed_backs/1.json
  def destroy
    @lcb_feed_back.destroy
    respond_to do |format|
      format.html { redirect_to lcb_feed_backs_url, notice: 'Lcb feed back was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lcb_feed_back
      @lcb_feed_back = LcbFeedBack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lcb_feed_back_params
      params.require(:lcb_feed_back).permit(:status, :user_id, :content, :owner_id, :create_uid, :write_uid, :id)
    end
end

app/helpers/apidocs_helper.rb
module ApidocsHelper
end

app/helpers/lcb_feed_backs_helper.rb
module LcbFeedBacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/yunweis_helper.rb
module YunweisHelper
end

app/views/lcb_feed_backs/_form.html.erb
<%= form_for(lcb_feed_back) do |f| %>
  <% if lcb_feed_back.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lcb_feed_back.errors.count, "error") %> prohibited this lcb_feed_back from being saved:</h2>

      <ul>
      <% lcb_feed_back.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :owner_id %>
    <%= f.text_field :owner_id %>
  </div>

  <div class="field">
    <%= f.label :create_uid %>
    <%= f.text_field :create_uid %>
  </div>

  <div class="field">
    <%= f.label :write_uid %>
    <%= f.text_field :write_uid %>
  </div>

  <div class="field">
    <%= f.label :id %>
    <%= f.text_field :id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lcb_feed_backs/edit.html.erb
<h1>Editing Lcb Feed Back</h1>

<%= render 'form', lcb_feed_back: @lcb_feed_back %>

<%= link_to 'Show', @lcb_feed_back %> |
<%= link_to 'Back', lcb_feed_backs_path %>

app/views/lcb_feed_backs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lcb Feed Backs</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>User</th>
      <th>Content</th>
      <th>Owner</th>
      <th>Create uid</th>
      <th>Write uid</th>
      <th>Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lcb_feed_backs.each do |lcb_feed_back| %>
      <tr>
        <td><%= lcb_feed_back.status %></td>
        <td><%= lcb_feed_back.user_id %></td>
        <td><%= lcb_feed_back.content %></td>
        <td><%= lcb_feed_back.owner_id %></td>
        <td><%= lcb_feed_back.create_uid %></td>
        <td><%= lcb_feed_back.write_uid %></td>
        <td><%= lcb_feed_back.id %></td>
        <td><%= link_to 'Show', lcb_feed_back %></td>
        <td><%= link_to 'Edit', edit_lcb_feed_back_path(lcb_feed_back) %></td>
        <td><%= link_to 'Destroy', lcb_feed_back, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lcb Feed Back', new_lcb_feed_back_path %>

app/views/lcb_feed_backs/new.html.erb
<h1>New Lcb Feed Back</h1>

<%= render 'form', lcb_feed_back: @lcb_feed_back %>

<%= link_to 'Back', lcb_feed_backs_path %>

app/views/lcb_feed_backs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @lcb_feed_back.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @lcb_feed_back.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @lcb_feed_back.content %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @lcb_feed_back.owner_id %>
</p>

<p>
  <strong>Create uid:</strong>
  <%= @lcb_feed_back.create_uid %>
</p>

<p>
  <strong>Write uid:</strong>
  <%= @lcb_feed_back.write_uid %>
</p>

<p>
  <strong>Id:</strong>
  <%= @lcb_feed_back.id %>
</p>

<%= link_to 'Edit', edit_lcb_feed_back_path(@lcb_feed_back) %> |
<%= link_to 'Back', lcb_feed_backs_path %>