config/routes.rb
Rails.application.routes.draw do
#match ':controller(/:action(/:id(.:format)))', :via => :all
  resources :lcb_access_items
  resources :lcb_account_sheets
  resources :lcb_accounts
  resources :lcb_actions
  resources :lcb_cash_coupon_defs
  resources :lcb_cash_coupons
  resources :lcb_feed_backs
  resources :lcb_image_positions
  resources :lcb_financing_target_tags
  resources :lcb_financing_target_positions
  resources :lcb_financing_target_bids
  resources :lcb_financing_targets
  resources :lcb_klines
  resources :lcb_manager_users
  resources :lcb_menus
  resources :lcb_pics
  resources :lcb_registries
  resources :lcb_templates
  resources :lcb_user_package_items
  resources :lcb_withdraw_financing_target_bid_items
  resources :lcb_withdraws
  resources :lcb_user_rewards
  resources :lcb_user_banks
  resources :lcb_users
  resources :yunweis
#  namespace :admin do
#    resources :users
#  end
  match '/reg', to: 'lcb_users#new', via: 'get'
  match '/login', to: 'lcb_users#login', via: 'get'
  match 'about_us.htm', to:'lcb_users#about_us.htm',via:'get'
  match '/sui_cun_bao', to: 'lcb_users#sui_cun_bao',via:"get"
  match '/login1', to: 'lcb_users#login1', via: 'post'
#    namespace :admin do
#          resources :sessions, only: [:new]
#              match '/signin', to: 'lcb_users#new', via: 'get'
#         end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/apidoc.rb
class Apidoc < ApplicationRecord
end

app/models/blog.rb
module Blog
  def self.table_name_prefix
    'blog_'
  end
end

app/models/lcb_access_item.rb
class LcbAccessItem < ApplicationRecord
end

app/models/lcb_account.rb
class LcbAccount < ApplicationRecord
end

app/models/lcb_action.rb
class LcbAction < ApplicationRecord
end

app/models/lcb_cash_coupon.rb
class LcbCashCoupon < ApplicationRecord
end

app/models/lcb_feed_back.rb
class LcbFeedBack < ApplicationRecord
end

app/models/lcb_kline.rb
class LcbKline < ApplicationRecord
end

app/models/lcb_menu.rb
class LcbMenu < ApplicationRecord
end

app/models/lcb_pic.rb
class LcbPic < ApplicationRecord
end

app/models/lcb_registry.rb
class LcbRegistry < ApplicationRecord
end

app/models/lcb_template.rb
class LcbTemplate < ApplicationRecord
end

app/models/lcb_user.rb
class LcbUser < ApplicationRecord
end

app/models/lcb_user_bank.rb
class LcbUserBank < ApplicationRecord
end

app/models/lcb_withdraw.rb
class LcbWithdraw < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/yunwei.rb
class Yunwei < ApplicationRecord
end

app/controllers/lcb_pics_controller.rb
class LcbPicsController < ApplicationController
  before_action :set_lcb_pic, only: [:show, :edit, :update, :destroy]

  # GET /lcb_pics
  # GET /lcb_pics.json
  def index
    @lcb_pics = LcbPic.all
  end

  # GET /lcb_pics/1
  # GET /lcb_pics/1.json
  def show
  end

  # GET /lcb_pics/new
  def new
    @lcb_pic = LcbPic.new
  end

  # GET /lcb_pics/1/edit
  def edit
  end

  # POST /lcb_pics
  # POST /lcb_pics.json
  def create
    @lcb_pic = LcbPic.new(lcb_pic_params)

    respond_to do |format|
      if @lcb_pic.save
        format.html { redirect_to @lcb_pic, notice: 'Lcb pic was successfully created.' }
        format.json { render :show, status: :created, location: @lcb_pic }
      else
        format.html { render :new }
        format.json { render json: @lcb_pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lcb_pics/1
  # PATCH/PUT /lcb_pics/1.json
  def update
    respond_to do |format|
      if @lcb_pic.update(lcb_pic_params)
        format.html { redirect_to @lcb_pic, notice: 'Lcb pic was successfully updated.' }
        format.json { render :show, status: :ok, location: @lcb_pic }
      else
        format.html { render :edit }
        format.json { render json: @lcb_pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lcb_pics/1
  # DELETE /lcb_pics/1.json
  def destroy
    @lcb_pic.destroy
    respond_to do |format|
      format.html { redirect_to lcb_pics_url, notice: 'Lcb pic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lcb_pic
      @lcb_pic = LcbPic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lcb_pic_params
      params.require(:lcb_pic).permit(:conntent_type, :name, :size, :path, :owner_id, :create_uid, :crite_uid, :id)
    end
end

app/helpers/apidocs_helper.rb
module ApidocsHelper
end

app/helpers/lcb_pics_helper.rb
module LcbPicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/yunweis_helper.rb
module YunweisHelper
end

app/views/lcb_pics/_form.html.erb
<%= form_for(lcb_pic) do |f| %>
  <% if lcb_pic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lcb_pic.errors.count, "error") %> prohibited this lcb_pic from being saved:</h2>

      <ul>
      <% lcb_pic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :conntent_type %>
    <%= f.text_field :conntent_type %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :size %>
    <%= f.number_field :size %>
  </div>

  <div class="field">
    <%= f.label :path %>
    <%= f.text_field :path %>
  </div>

  <div class="field">
    <%= f.label :owner_id %>
    <%= f.text_field :owner_id %>
  </div>

  <div class="field">
    <%= f.label :create_uid %>
    <%= f.text_field :create_uid %>
  </div>

  <div class="field">
    <%= f.label :crite_uid %>
    <%= f.text_field :crite_uid %>
  </div>

  <div class="field">
    <%= f.label :id %>
    <%= f.text_field :id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lcb_pics/edit.html.erb
<h1>Editing Lcb Pic</h1>

<%= render 'form', lcb_pic: @lcb_pic %>

<%= link_to 'Show', @lcb_pic %> |
<%= link_to 'Back', lcb_pics_path %>

app/views/lcb_pics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lcb Pics</h1>

<table>
  <thead>
    <tr>
      <th>Conntent type</th>
      <th>Name</th>
      <th>Size</th>
      <th>Path</th>
      <th>Owner</th>
      <th>Create uid</th>
      <th>Crite uid</th>
      <th>Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lcb_pics.each do |lcb_pic| %>
      <tr>
        <td><%= lcb_pic.conntent_type %></td>
        <td><%= lcb_pic.name %></td>
        <td><%= lcb_pic.size %></td>
        <td><%= lcb_pic.path %></td>
        <td><%= lcb_pic.owner_id %></td>
        <td><%= lcb_pic.create_uid %></td>
        <td><%= lcb_pic.crite_uid %></td>
        <td><%= lcb_pic.id %></td>
        <td><%= link_to 'Show', lcb_pic %></td>
        <td><%= link_to 'Edit', edit_lcb_pic_path(lcb_pic) %></td>
        <td><%= link_to 'Destroy', lcb_pic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lcb Pic', new_lcb_pic_path %>

app/views/lcb_pics/new.html.erb
<h1>New Lcb Pic</h1>

<%= render 'form', lcb_pic: @lcb_pic %>

<%= link_to 'Back', lcb_pics_path %>

app/views/lcb_pics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Conntent type:</strong>
  <%= @lcb_pic.conntent_type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @lcb_pic.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @lcb_pic.size %>
</p>

<p>
  <strong>Path:</strong>
  <%= @lcb_pic.path %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @lcb_pic.owner_id %>
</p>

<p>
  <strong>Create uid:</strong>
  <%= @lcb_pic.create_uid %>
</p>

<p>
  <strong>Crite uid:</strong>
  <%= @lcb_pic.crite_uid %>
</p>

<p>
  <strong>Id:</strong>
  <%= @lcb_pic.id %>
</p>

<%= link_to 'Edit', edit_lcb_pic_path(@lcb_pic) %> |
<%= link_to 'Back', lcb_pics_path %>