config/routes.rb
Rails.application.routes.draw do
#match ':controller(/:action(/:id(.:format)))', :via => :all
  resources :lcb_access_items
  resources :lcb_account_sheets
  resources :lcb_accounts
  resources :lcb_actions
  resources :lcb_cash_coupon_defs
  resources :lcb_cash_coupons
  resources :lcb_feed_backs
  resources :lcb_image_positions
  resources :lcb_financing_target_tags
  resources :lcb_financing_target_positions
  resources :lcb_financing_target_bids
  resources :lcb_financing_targets
  resources :lcb_klines
  resources :lcb_manager_users
  resources :lcb_menus
  resources :lcb_pics
  resources :lcb_registries
  resources :lcb_templates
  resources :lcb_user_package_items
  resources :lcb_withdraw_financing_target_bid_items
  resources :lcb_withdraws
  resources :lcb_user_rewards
  resources :lcb_user_banks
  resources :lcb_users
  resources :yunweis
#  namespace :admin do
#    resources :users
#  end
  match '/reg', to: 'lcb_users#new', via: 'get'
  match '/login', to: 'lcb_users#login', via: 'get'
  match 'about_us.htm', to:'lcb_users#about_us.htm',via:'get'
  match '/sui_cun_bao', to: 'lcb_users#sui_cun_bao',via:"get"
  match '/login1', to: 'lcb_users#login1', via: 'post'
#    namespace :admin do
#          resources :sessions, only: [:new]
#              match '/signin', to: 'lcb_users#new', via: 'get'
#         end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/apidoc.rb
class Apidoc < ApplicationRecord
end

app/models/blog.rb
module Blog
  def self.table_name_prefix
    'blog_'
  end
end

app/models/lcb_access_item.rb
class LcbAccessItem < ApplicationRecord
end

app/models/lcb_account.rb
class LcbAccount < ApplicationRecord
end

app/models/lcb_action.rb
class LcbAction < ApplicationRecord
end

app/models/lcb_cash_coupon.rb
class LcbCashCoupon < ApplicationRecord
end

app/models/lcb_feed_back.rb
class LcbFeedBack < ApplicationRecord
end

app/models/lcb_kline.rb
class LcbKline < ApplicationRecord
end

app/models/lcb_menu.rb
class LcbMenu < ApplicationRecord
end

app/models/lcb_pic.rb
class LcbPic < ApplicationRecord
end

app/models/lcb_registry.rb
class LcbRegistry < ApplicationRecord
end

app/models/lcb_template.rb
class LcbTemplate < ApplicationRecord
end

app/models/lcb_user.rb
class LcbUser < ApplicationRecord
end

app/models/lcb_user_bank.rb
class LcbUserBank < ApplicationRecord
end

app/models/lcb_withdraw.rb
class LcbWithdraw < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/yunwei.rb
class Yunwei < ApplicationRecord
end

app/controllers/lcb_klines_controller.rb
class LcbKlinesController < ApplicationController
  before_action :set_lcb_kline, only: [:show, :edit, :update, :destroy]

  # GET /lcb_klines
  # GET /lcb_klines.json
  def index
    @lcb_klines = LcbKline.all
  end

  # GET /lcb_klines/1
  # GET /lcb_klines/1.json
  def show
  end

  # GET /lcb_klines/new
  def new
    @lcb_kline = LcbKline.new
  end

  # GET /lcb_klines/1/edit
  def edit
  end

  # POST /lcb_klines
  # POST /lcb_klines.json
  def create
    @lcb_kline = LcbKline.new(lcb_kline_params)

    respond_to do |format|
      if @lcb_kline.save
        format.html { redirect_to @lcb_kline, notice: 'Lcb kline was successfully created.' }
        format.json { render :show, status: :created, location: @lcb_kline }
      else
        format.html { render :new }
        format.json { render json: @lcb_kline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lcb_klines/1
  # PATCH/PUT /lcb_klines/1.json
  def update
    respond_to do |format|
      if @lcb_kline.update(lcb_kline_params)
        format.html { redirect_to @lcb_kline, notice: 'Lcb kline was successfully updated.' }
        format.json { render :show, status: :ok, location: @lcb_kline }
      else
        format.html { render :edit }
        format.json { render json: @lcb_kline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lcb_klines/1
  # DELETE /lcb_klines/1.json
  def destroy
    @lcb_kline.destroy
    respond_to do |format|
      format.html { redirect_to lcb_klines_url, notice: 'Lcb kline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lcb_kline
      @lcb_kline = LcbKline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lcb_kline_params
      params.require(:lcb_kline).permit(:type, :open_price, :height_price, :low_price, :closed_price, :id, :owner_id, :create_uid, :write_uid)
    end
end

app/helpers/apidocs_helper.rb
module ApidocsHelper
end

app/helpers/lcb_klines_helper.rb
module LcbKlinesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/yunweis_helper.rb
module YunweisHelper
end

app/views/lcb_klines/_form.html.erb
<%= form_for(lcb_kline) do |f| %>
  <% if lcb_kline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lcb_kline.errors.count, "error") %> prohibited this lcb_kline from being saved:</h2>

      <ul>
      <% lcb_kline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %>
    <%= f.text_field :type %>
  </div>

  <div class="field">
    <%= f.label :open_price %>
    <%= f.text_field :open_price %>
  </div>

  <div class="field">
    <%= f.label :height_price %>
    <%= f.text_field :height_price %>
  </div>

  <div class="field">
    <%= f.label :low_price %>
    <%= f.text_field :low_price %>
  </div>

  <div class="field">
    <%= f.label :closed_price %>
    <%= f.text_field :closed_price %>
  </div>

  <div class="field">
    <%= f.label :id %>
    <%= f.text_field :id %>
  </div>

  <div class="field">
    <%= f.label :owner_id %>
    <%= f.text_field :owner_id %>
  </div>

  <div class="field">
    <%= f.label :create_uid %>
    <%= f.text_field :create_uid %>
  </div>

  <div class="field">
    <%= f.label :write_uid %>
    <%= f.text_field :write_uid %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lcb_klines/edit.html.erb
<h1>Editing Lcb Kline</h1>

<%= render 'form', lcb_kline: @lcb_kline %>

<%= link_to 'Show', @lcb_kline %> |
<%= link_to 'Back', lcb_klines_path %>

app/views/lcb_klines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lcb Klines</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Open price</th>
      <th>Height price</th>
      <th>Low price</th>
      <th>Closed price</th>
      <th>Id</th>
      <th>Owner</th>
      <th>Create uid</th>
      <th>Write uid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lcb_klines.each do |lcb_kline| %>
      <tr>
        <td><%= lcb_kline.type %></td>
        <td><%= lcb_kline.open_price %></td>
        <td><%= lcb_kline.height_price %></td>
        <td><%= lcb_kline.low_price %></td>
        <td><%= lcb_kline.closed_price %></td>
        <td><%= lcb_kline.id %></td>
        <td><%= lcb_kline.owner_id %></td>
        <td><%= lcb_kline.create_uid %></td>
        <td><%= lcb_kline.write_uid %></td>
        <td><%= link_to 'Show', lcb_kline %></td>
        <td><%= link_to 'Edit', edit_lcb_kline_path(lcb_kline) %></td>
        <td><%= link_to 'Destroy', lcb_kline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lcb Kline', new_lcb_kline_path %>

app/views/lcb_klines/new.html.erb
<h1>New Lcb Kline</h1>

<%= render 'form', lcb_kline: @lcb_kline %>

<%= link_to 'Back', lcb_klines_path %>

app/views/lcb_klines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @lcb_kline.type %>
</p>

<p>
  <strong>Open price:</strong>
  <%= @lcb_kline.open_price %>
</p>

<p>
  <strong>Height price:</strong>
  <%= @lcb_kline.height_price %>
</p>

<p>
  <strong>Low price:</strong>
  <%= @lcb_kline.low_price %>
</p>

<p>
  <strong>Closed price:</strong>
  <%= @lcb_kline.closed_price %>
</p>

<p>
  <strong>Id:</strong>
  <%= @lcb_kline.id %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @lcb_kline.owner_id %>
</p>

<p>
  <strong>Create uid:</strong>
  <%= @lcb_kline.create_uid %>
</p>

<p>
  <strong>Write uid:</strong>
  <%= @lcb_kline.write_uid %>
</p>

<%= link_to 'Edit', edit_lcb_kline_path(@lcb_kline) %> |
<%= link_to 'Back', lcb_klines_path %>